/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.inspection.service;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class InspectionCoreService{private final EntityManager em;/**
                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                            */
public InspectionCoreService(EntityManager em){this.em=em;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionPlan createPlan(CreatePlanRequest r){if(!em.createQuery("select p from InspectionPlanEntity p where p.planNo=:no",InspectionPlan.class).setParameter("no",r.planNo()).getResultList().isEmpty())throw conflict("巡检计划编号已存在");List<String>points=r.pointCodes().stream().map(String::trim).filter(v->!v.isBlank()).distinct().toList();if(points.size()!=r.pointCodes().size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"巡检点位不能为空或重复");InspectionPlan p=new InspectionPlan(r.planNo(),r.planName(),r.routeName(),r.frequency(),r.owner(),String.join(",",points));em.persist(p);return p;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public List<InspectionPlan>plans(String status){return em.createQuery("select p from InspectionPlanEntity p where (:s is null or p.status=:s) order by p.planNo",InspectionPlan.class).setParameter("s",blank(status)?null:status).getResultList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionPlan publishPlan(Long id){InspectionPlan p=planLocked(id);if(!"DRAFT".equals(p.status))throw conflict("仅草稿计划可以发布");p.status="PUBLISHED";p.publishedBy=operator();p.publishedAt=LocalDateTime.now();return p;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionTask generateTask(Long planId,GenerateTaskRequest r){InspectionPlan p=planLocked(planId);if(!"PUBLISHED".equals(p.status))throw conflict("仅已发布巡检计划可以生成任务");if(!byNo(r.taskNo()).isEmpty())throw conflict("巡检任务编号已存在");InspectionTask t=new InspectionTask(r.taskNo(),p.planNo,p.routeName,r.assignee(),p.points().size(),r.dueAt());t.planId=p.id;em.persist(t);return t;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionTask createTask(CreateTaskRequest r){if(!byNo(r.taskNo()).isEmpty())throw conflict("巡检任务编号已存在");InspectionTask t=new InspectionTask(r.taskNo(),r.planNo(),r.routeName(),r.assignee(),r.plannedPoints(),r.dueAt());em.persist(t);return t;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public List<InspectionTask>tasks(String status){return em.createQuery("select t from InspectionCoreTask t where (:s is null or t.status=:s) order by t.dueAt",InspectionTask.class).setParameter("s",blank(status)?null:status).getResultList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionTask start(Long id){InspectionTask t=taskLocked(id);if(!"PLANNED".equals(t.status))throw conflict("只有已计划任务可以开始");t.status="IN_PROGRESS";t.startedAt=LocalDateTime.now();return t;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public PointResult recordPoint(Long id,PointRequest r){InspectionTask t=taskLocked(id);if(!"IN_PROGRESS".equals(t.status))throw conflict("仅执行中的任务可以提交点位结果");if(t.planId!=null&&!plan(t.planId).points().contains(r.pointCode()))throw conflict("点位不属于任务关联的已发布巡检计划");List<PointResult>old=em.createQuery("select p from InspectionPointResult p where p.taskId=:id and p.pointCode=:code",PointResult.class).setParameter("id",id).setParameter("code",r.pointCode()).getResultList();if(!old.isEmpty())return old.getFirst();if(t.completedPoints>=t.plannedPoints)throw conflict("已达到计划点位数，不能继续提交");PointResult p=new PointResult(t.id,r.pointCode(),r.passed(),r.reading(),r.evidenceHash(),operator());em.persist(p);t.completedPoints++;if(!r.passed())t.failedPoints++;return p;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public List<PointResult>points(Long id){task(id);return em.createQuery("select p from InspectionPointResult p where p.taskId=:id order by p.inspectedAt",PointResult.class).setParameter("id",id).getResultList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public Hazard createHazard(Long taskId,HazardRequest r){InspectionTask t=taskLocked(taskId);if(!"IN_PROGRESS".equals(t.status))throw conflict("仅执行中的任务可以登记隐患");if(!hazardByNo(r.hazardNo()).isEmpty())throw conflict("隐患编号已存在");Hazard h=new Hazard(t.id,r.hazardNo(),r.title(),r.riskLevel(),r.owner(),r.dueDate());em.persist(h);return h;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public List<Hazard>hazards(Long taskId){task(taskId);return em.createQuery("select h from InspectionHazard h where h.taskId=:id order by h.dueDate",Hazard.class).setParameter("id",taskId).getResultList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public Hazard contain(Long id,ActionRequest r){Hazard h=hazardLocked(id);if(!"OPEN".equals(h.status))throw conflict("仅待处置隐患可以执行临时控制");h.status="CONTAINED";h.containment=r.detail();h.containedAt=LocalDateTime.now();return h;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public Hazard rectify(Long id,RectifyRequest r){Hazard h=hazardLocked(id);if(!Set.of("OPEN","CONTAINED").contains(h.status))throw conflict("当前隐患状态不能提交整改");if("CRITICAL".equals(h.riskLevel)&&h.containedAt==null)throw conflict("重大隐患必须先完成临时控制");h.status="RECTIFIED";h.rectification=r.rectification();h.evidenceHash=r.evidenceHash();h.rectifiedBy=operator();h.rectifiedAt=LocalDateTime.now();return h;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public Hazard verify(Long id,VerifyRequest r){Hazard h=hazardLocked(id);if(!"RECTIFIED".equals(h.status))throw conflict("仅已整改隐患可以复核");if(operator().equals(h.rectifiedBy))throw conflict("整改人与复核人必须职责分离");if(r.approved()){h.status="VERIFIED";h.verifiedAt=LocalDateTime.now();h.verifiedBy=operator();}else{h.status="OPEN";h.rejectionReason=r.remark();}return h;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public InspectionTask close(Long id){InspectionTask t=taskLocked(id);if(!"IN_PROGRESS".equals(t.status))throw conflict("仅执行中的任务可以关闭");if(t.completedPoints!=t.plannedPoints)throw conflict("存在未完成巡检点位");long open=em.createQuery("select count(h) from InspectionHazard h where h.taskId=:id and h.status<>'VERIFIED'",Long.class).setParameter("id",id).getSingleResult();if(open>0)throw conflict("存在未复核销项隐患");t.status="CLOSED";t.closedAt=LocalDateTime.now();return t;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public InspectionSummary summary(){LocalDateTime now=LocalDateTime.now();List<InspectionTask>all=tasks(null);long overdue=all.stream().filter(t->!"CLOSED".equals(t.status)&&t.dueAt.isBefore(now)).count();long openHazards=em.createQuery("select count(h) from InspectionHazard h where h.status<>'VERIFIED'",Long.class).getSingleResult();long critical=em.createQuery("select count(h) from InspectionHazard h where h.riskLevel='CRITICAL' and h.status<>'VERIFIED'",Long.class).getSingleResult();return new InspectionSummary(all.size(),all.stream().filter(t->"CLOSED".equals(t.status)).count(),overdue,openHazards,critical);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<InspectionTask>byNo(String no){return em.createQuery("select t from InspectionCoreTask t where t.taskNo=:no",InspectionTask.class).setParameter("no",no).getResultList();}/**
                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                         */
private List<Hazard>hazardByNo(String no){return em.createQuery("select h from InspectionHazard h where h.hazardNo=:no",Hazard.class).setParameter("no",no).getResultList();}/**
                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                      */
private InspectionPlan plan(Long id){InspectionPlan p=em.find(InspectionPlan.class,id);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"巡检计划不存在");return p;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
private InspectionPlan planLocked(Long id){InspectionPlan p=em.find(InspectionPlan.class,id,LockModeType.PESSIMISTIC_WRITE);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"巡检计划不存在");return p;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
private InspectionTask task(Long id){InspectionTask t=em.find(InspectionTask.class,id);if(t==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"巡检任务不存在");return t;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
private InspectionTask taskLocked(Long id){InspectionTask t=em.find(InspectionTask.class,id,LockModeType.PESSIMISTIC_WRITE);if(t==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"巡检任务不存在");return t;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
private Hazard hazardLocked(Long id){Hazard h=em.find(Hazard.class,id,LockModeType.PESSIMISTIC_WRITE);if(h==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"隐患不存在");return h;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private boolean blank(String v){return v==null||v.isBlank();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
private String operator(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record CreatePlanRequest(@NotBlank@Size(max=40)String planNo,@NotBlank@Size(max=120)String planName,@NotBlank@Size(max=120)String routeName,@NotNull@Pattern(regexp="DAILY|WEEKLY|MONTHLY|ON_DEMAND")String frequency,@NotBlank@Size(max=80)String owner,@NotNull@Size(min=1,max=50)List<@NotBlank@Size(max=50)String> pointCodes){}/**
                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                             */
public record GenerateTaskRequest(@NotBlank@Size(max=40)String taskNo,@NotBlank@Size(max=80)String assignee,@Future LocalDateTime dueAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record CreateTaskRequest(@NotBlank@Size(max=40)String taskNo,@NotBlank@Size(max=40)String planNo,@NotBlank@Size(max=120)String routeName,@NotBlank@Size(max=80)String assignee,@Positive int plannedPoints,@Future LocalDateTime dueAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record PointRequest(@NotBlank@Size(max=50)String pointCode,boolean passed,@Size(max=100)String reading,@Pattern(regexp="[a-fA-F0-9]{64}")String evidenceHash){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
public record HazardRequest(@NotBlank@Size(max=40)String hazardNo,@NotBlank@Size(max=160)String title,@Pattern(regexp="LOW|MEDIUM|HIGH|CRITICAL")String riskLevel,@NotBlank@Size(max=80)String owner,@FutureOrPresent LocalDate dueDate){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record ActionRequest(@NotBlank@Size(max=500)String detail){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record RectifyRequest(@NotBlank@Size(max=1000)String rectification,@Pattern(regexp="[a-fA-F0-9]{64}")String evidenceHash){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public record VerifyRequest(boolean approved,@Size(max=500)String remark){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record InspectionSummary(long totalTasks,long closedTasks,long overdueTasks,long openHazards,long openCriticalHazards){}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Entity(name="InspectionPlanEntity")@Table(name="inspection_plans",uniqueConstraints=@UniqueConstraint(columnNames="planNo"))public static class InspectionPlan{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;@Column(nullable=false,length=40)public String planNo;@Column(nullable=false,length=120)public String planName;@Column(nullable=false,length=120)public String routeName;@Column(nullable=false,length=20)public String frequency;@Column(nullable=false,length=80)public String owner;@Column(nullable=false,length=2000)public String pointCodesCsv;@Column(nullable=false,length=20)public String status;@Column(length=80)public String publishedBy;public LocalDateTime createdAt;public LocalDateTime publishedAt;@Version public long version;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
protected InspectionPlan(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
InspectionPlan(String no,String name,String route,String frequency,String owner,String points){this.planNo=no;this.planName=name;this.routeName=route;this.frequency=frequency;this.owner=owner;this.pointCodesCsv=points;this.status="DRAFT";this.createdAt=LocalDateTime.now();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public List<String>getPointCodes(){return points();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
List<String>points(){return Arrays.asList(pointCodesCsv.split(","));}}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Entity(name="InspectionCoreTask")@Table(name="inspection_core_tasks",uniqueConstraints=@UniqueConstraint(columnNames="taskNo"))public static class InspectionTask{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long planId;@Column(nullable=false,length=40)public String taskNo;@Column(nullable=false,length=40)public String planNo;@Column(nullable=false,length=120)public String routeName;@Column(nullable=false,length=80)public String assignee;public int plannedPoints;public int completedPoints;public int failedPoints;@Column(nullable=false,length=20)public String status;public LocalDateTime dueAt;public LocalDateTime startedAt;public LocalDateTime closedAt;@Version public long version;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
protected InspectionTask(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
InspectionTask(String no,String plan,String route,String assignee,int points,LocalDateTime due){this.taskNo=no;this.planNo=plan;this.routeName=route;this.assignee=assignee;this.plannedPoints=points;this.dueAt=due;this.status="PLANNED";}}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Entity(name="InspectionPointResult")@Table(name="inspection_point_results",uniqueConstraints=@UniqueConstraint(columnNames={"taskId","pointCode"}))public static class PointResult{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long taskId;@Column(nullable=false,length=50)public String pointCode;public boolean passed;@Column(length=100)public String reading;@Column(nullable=false,length=64)public String evidenceHash;@Column(nullable=false,length=80)public String inspectedBy;public LocalDateTime inspectedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
protected PointResult(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
PointResult(Long taskId,String point,boolean passed,String reading,String hash,String by){this.taskId=taskId;this.pointCode=point;this.passed=passed;this.reading=reading;this.evidenceHash=hash;this.inspectedBy=by;this.inspectedAt=LocalDateTime.now();}}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Entity(name="InspectionHazard")@Table(name="inspection_hazards",uniqueConstraints=@UniqueConstraint(columnNames="hazardNo"))public static class Hazard{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long taskId;@Column(nullable=false,length=40)public String hazardNo;@Column(nullable=false,length=160)public String title;@Column(nullable=false,length=12)public String riskLevel;@Column(nullable=false,length=80)public String owner;public LocalDate dueDate;@Column(nullable=false,length=20)public String status;@Column(length=500)public String containment;@Column(length=1000)public String rectification;@Column(length=64)public String evidenceHash;@Column(length=80)public String rectifiedBy;@Column(length=80)public String verifiedBy;@Column(length=500)public String rejectionReason;public LocalDateTime containedAt;public LocalDateTime rectifiedAt;public LocalDateTime verifiedAt;@Version public long version;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
protected Hazard(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
Hazard(Long taskId,String no,String title,String risk,String owner,LocalDate due){this.taskId=taskId;this.hazardNo=no;this.title=title;this.riskLevel=risk;this.owner=owner;this.dueDate=due;this.status="OPEN";}}
}
